# Site settings
title: Fei Blog
SEOTitle: 高飞的博客 | Fei Blog
header-img: img/home-bg.jpg
email: iostouch@126.com
description: "关于前端与设计、黑客与画家 | 高飞，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @JsonSmith高飞 的个人博客，与你一起探索未知的世界。"
keyword: "高飞, 移动端, 开发, 设计, 博客, 个人网站, 互联网, iOS"
url: "https://feipages.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    feipages
twitter_username:   JsonSmith
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: Json Smith

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: '9ffab98fa7af4f1a8bb4afa5f887fd7f'

# Google Analytics
ga_track_id: 'UA-117666819-1'            # Format: UA-xxxxxx-xx
ga_domain: ipages.top
#ga_domain: feipages.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "做做移动开发，写写serve，<br>注重过程，就有结果"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "喵神",
        href: "https://onevcat.com/"
    },{
        title: "唐巧",
        href: "http://blog.devtang.com/"
    },{
        title: "NSHipster",
        href: "http://nshipster.cn/"
    },{
        title: "老谭笔记",
        href: "http://www.tanhao.me/"
    },{
        title: "玉令天下的博客",
        href: "http://yulingtianxia.com/"
  }
    ,{
        title: "念茜的博客",
        href: "https://nianxi.net/"
    },{
        title: "sunnyxx的技术博客",
        href: "http://blog.sunnyxx.com/"
    },{
        title: "阿毛的蛋疼地",
        href: "http://xiangwangfeng.com/"
    },{
        title: "I'm TualatriX",
        href: "https://imtx.me/"
    },{
        title: "Nico",
        href: "http://blog.inico.me/"
    },{
        title: "王中周的技术博客-->实用",
        href: "http://foggry.com/"
    },{
        title: "码农人生-->音视频",
        href: "http://msching.github.io/"
    },{
        title: "JokerJason-->java",
        href: "http://www.cnblogs.com/jokerjason"
  },{
        title: "向晨宇-->实用",
        href: "http://www.iosxxx.com/"
 },{
        title: "里脊串的开发随笔",
        href: "http://adad184.com/"
  
},{
        title: "Tian Wei Yu-->架构",
        href: "https://casatwy.com/"
},{
        title: "zblade-->游戏",
        href: "http://www.cnblogs.com/zblade/"
},{
        title: "coderyi-->",
        href: "http://coderyi.com/"
},{
        title: "雷纯锋的技术博客-->实用",
        href: "http://blog.leichunfeng.com/"
}
]
